// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "shellPath": string;
      "pythonPath": string;
      "mistralApiKey": string;
      "llmApiKey": string;
      "llmApiUrl": string;
      "llmModel": string;
      "reviewGeneratedHtml": boolean;
      "inlineImages": boolean;
      "sourceLanguage": string;
      "targetLanguage": string;
    };
  }
}
